### ISSUE TITLE
Unable to Scan for BLE Devices: I/NAVIGINE_LOG: Failed to scan BLE with error code: 2 (Ble scan failed)

### ISSUE THREAD

**Issue by liborioc1** [Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0#13]
I am using the SDK for my own project following the code in this github. Upon a set of runs approximately 3-5 there are no issues with navigation and positioning. However, after those fixed runs an error begins to popup as a navigine info log.

V/FA: Connecting to remote service
    Connection attempt already in progress
D/BluetoothAdapter: isLeEnabled(): ON
D/BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0
D/BluetoothAdapter: isLeEnabled(): ON
D/BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0
D/NAVIGINE_LOG: Start scanning bluetooth
I/NAVIGINE_LOG: Connection established!
    Setting up the SSL/TLS structure...
    Performing the SSL/TLS handshake...
I/NAVIGINE_LOG: Failed to scan BLE with error code: 2 (Ble scan failed)
D/NAVIGINE_LOG: Scan Error Code: 2
I/NAVIGINE_LOG: Failed to scan BLE with error code: 2 (Ble scan failed)
D/NAVIGINE_LOG: Scan Error Code: 2
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 2

Error code 2 corresponds to SCAN_FAILED_APPLICATION_REGISTRATION_FAILED from the ScanCallBack Android class (https://developer.android.com/reference/android/bluetooth/le/ScanCallback#SCAN_FAILED_APPLICATION_REGISTRATION_FAILED)

Based on my research is seems as though the phones bluetooth resources are completely occupied and thus cannot register another BluetoothLeScanner.

D/NAVIGINE_LOG: Position update error (code: 30)
is the log produced from the positioning listener as a result of the scanner never being registered.

Steps: 
1. Run the application until the positioning begins
2. Kill the app
3. reopen the app
4. Repeat until positioning no longer occurs.

The app should be able to discover beacons and carry out positioning even when opening and closing on multiple occasions.

The device I'm using is the Google Pixel 4a, running Android 11.

I am able to exit this error state upon restarting the device.

**Comment by Salma-Elmahallawy** [comment]
> I am using the SDK for my own project following the code in this github. Upon a set of runs approximately 3-5 there are no issues with navigation and positioning. However, after those fixed runs an error begins to popup as a navigine info log.
> 
> V/FA: Connecting to remote service Connection attempt already in progress D/BluetoothAdapter: isLeEnabled(): ON D/BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0 D/BluetoothAdapter: isLeEnabled(): ON D/BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0 D/NAVIGINE_LOG: Start scanning bluetooth I/NAVIGINE_LOG: Connection established! Setting up the SSL/TLS structure... Performing the SSL/TLS handshake... I/NAVIGINE_LOG: Failed to scan BLE with error code: 2 (Ble scan failed) D/NAVIGINE_LOG: Scan Error Code: 2 I/NAVIGINE_LOG: Failed to scan BLE with error code: 2 (Ble scan failed) D/NAVIGINE_LOG: Scan Error Code: 2 D/FA: Connected to remote service V/FA: Processing queued up service tasks: 2
> 
> Error code 2 corresponds to SCAN_FAILED_APPLICATION_REGISTRATION_FAILED from the ScanCallBack Android class (https://developer.android.com/reference/android/bluetooth/le/ScanCallback#SCAN_FAILED_APPLICATION_REGISTRATION_FAILED)
> 
> Based on my research is seems as though the phones bluetooth resources are completely occupied and thus cannot register another BluetoothLeScanner.
> 
> D/NAVIGINE_LOG: Position update error (code: 30) is the log produced from the positioning listener as a result of the scanner never being registered.
> 
> Steps:
> 
> 1. Run the application until the positioning begins
> 2. Kill the app
> 3. reopen the app
> 4. Repeat until positioning no longer occurs.
> 
> The app should be able to discover beacons and carry out positioning even when opening and closing on multiple occasions.
> 
> The device I'm using is the Google Pixel 4a, running Android 11.
> 
> I am able to exit this error state upon restarting the device.

I am attaching the log file for when the error happens. There is no information about the Bluetooth scanning, probably because the adapter fails as mentioned by @liborioc1 

[position_error_log.docx](https://github.com/Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0/files/7883591/position_error_log.docx)

**Comment by PavelTychinin** [comment]
> > I am using the SDK for my own project following the code in this github. Upon a set of runs approximately 3-5 there are no issues with navigation and positioning. However, after those fixed runs an error begins to popup as a navigine info log.
> > V/FA: Connecting to remote service Connection attempt already in progress D/BluetoothAdapter: isLeEnabled(): ON D/BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0 D/BluetoothAdapter: isLeEnabled(): ON D/BluetoothLeScanner: onScannerRegistered() - status=133 scannerId=0 mScannerId=0 D/NAVIGINE_LOG: Start scanning bluetooth I/NAVIGINE_LOG: Connection established! Setting up the SSL/TLS structure... Performing the SSL/TLS handshake... I/NAVIGINE_LOG: Failed to scan BLE with error code: 2 (Ble scan failed) D/NAVIGINE_LOG: Scan Error Code: 2 I/NAVIGINE_LOG: Failed to scan BLE with error code: 2 (Ble scan failed) D/NAVIGINE_LOG: Scan Error Code: 2 D/FA: Connected to remote service V/FA: Processing queued up service tasks: 2
> > Error code 2 corresponds to SCAN_FAILED_APPLICATION_REGISTRATION_FAILED from the ScanCallBack Android class (https://developer.android.com/reference/android/bluetooth/le/ScanCallback#SCAN_FAILED_APPLICATION_REGISTRATION_FAILED)
> > Based on my research is seems as though the phones bluetooth resources are completely occupied and thus cannot register another BluetoothLeScanner.
> > D/NAVIGINE_LOG: Position update error (code: 30) is the log produced from the positioning listener as a result of the scanner never being registered.
> > Steps:
> > 
> > 1. Run the application until the positioning begins
> > 2. Kill the app
> > 3. reopen the app
> > 4. Repeat until positioning no longer occurs.
> > 
> > The app should be able to discover beacons and carry out positioning even when opening and closing on multiple occasions.
> > The device I'm using is the Google Pixel 4a, running Android 11.
> > I am able to exit this error state upon restarting the device.
> 
> @PavelTychinin I am attaching the log file for when the error happens. There is no information about the Bluetooth scanning, probably because the adapter fails as mentioned by @liborioc1
> 
> [position_error_log.docx](https://github.com/Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0/files/7883591/position_error_log.docx)

Hi @Salma-Elmahallawy 

Thnx for reply. This error may appear during the development process when the project is assembled and launched in Android Studio. We are working on fixing this bug. As a quick fix, you can delete the application manually or restart the phone. In the production version, everything should work well
