### ISSUE TITLE
onPositionUpdated(Position position) returning wrong position

### ISSUE THREAD

**Issue by Salma-Elmahallawy** [Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0#14]
**Describe the bug**
The Position returned in the play store's application is correct, but the position returned from the latest code in the repository is incorrect. In the demo app here, the onPositionListener returns very accurate positions in some parts of one hallway, but wrong ones in another part of the same hallway. 

Note: the beacons detected and distances to them are correct on both. The position is not though.

**To Reproduce**
Either start positioning in the section of the hallway where I am not positioned properly or start from another correct position then move towards it.

**Expected behavior**
Correct Position returned from the PositionListener's callback.

**Screenshots**
The parts with green checkmarks. I am not located correctly in the red section.
![image](https://user-images.githubusercontent.com/50728005/150197408-2b52df5c-9f0b-426e-879e-80d7cc6d4b30.png)

This shows how it is locating me wrong at two different places:
![image](https://user-images.githubusercontent.com/50728005/150205205-719ce570-8db3-4a48-8757-d87f6c2700ff.png)

Beacon distribution is the same (alternating between the two walls along the hallway). It works perfectly everywhere on the app from the play store but not using the SDK or demo app.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - OS: Android
 - Version: 11

**Comment by Salma-Elmahallawy** [comment]
Hi, the new aar version fixed this issue. Thanks.

**Comment by PavelTychinin** [comment]
@Salma-Elmahallawy Hi.
Hope everything good on your side.
Can you explain, what's going wrong now? What version of application do you use?

**Comment by Salma-Elmahallawy** [comment]
> @Salma-Elmahallawy Hi.
> 
> Hope everything good on your side.
> 
> Can you explain, what's going wrong now? What version of application do you use?

Hi @PavelTychinin! I hope everything is good on your side as well. The issue is that the isPositionUpdated returns the wrong point in the hallways I specified in the issue. Although the app is reading the signals and the distance to them correctly, the point is incorrect and therefore it is positioning me wrong. 

It works fine in the hallways with the green check mark in the image but not in any other place and we do not know why. I have also attached the second image to show how the positioning is incorrect.
We even have barriers around rooms, and sometimes it positions me inside them instead of placing me in the right hallway.

I am using the latest version in this repository. Please note that this error does not happen in the app on the android app store.

Thanks!

**Comment by tim-chikichev-navigine** [comment]
@Salma-Elmahallawy hello. I'm working on your problem now. 

Can you please records logs from your location using the app you are currently having issues with?
If you provide us with data of your map and recorded logs we will evaluate your problem as soon as possible.

You can refer to this guide for how to record logs properly: https://docs.navigine.com/en/Using_Navigine_Application_for_Android

Please, record 2-3 logs with checkpoints, 1+ minute long each. With this we will check that you location was set up correctly and find other possible problems.

In case of any questions and issues, please do not hesitate to ask us directly.

**Comment by notenoughsun** [comment]
@Salma-Elmahallawy just to keep it clear.
Checkpoints are just for us for debugging. 

If you manage to have our app and record with checkpoints - we will understand details about your location. 
And then we can check your logs from any version of sdk you have issues with. 

Best option is to have logs from the same phone with best scannings options (android usually). 

Contact us here or via mail on the official website. We may discuss details after we have a closer look on the problem.
