### ISSUE TITLE
NavigationManager: Position update error (code: 30)

### ISSUE THREAD

**Issue by novseje** [Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0#7]
**Describe the bug**
The application has code like this:
```
NavigationManager.addPositionListener(new PositionListener() {
  @Override
  public void onPositionUpdated(Position position) {
    Log.d("NavigineApp", "onPositionUpdated()");
    CurrentPosition = position;
  }

  @Override
  public void onPositionError(Error error) {
    Log.d("NavigineApp", "onPositionError(). Message: " + error.getMessage());
  }
});
```
At the same time, I get the following error:
_Message: **Position update error (code: 30)**_

After a few minutes of running the application, the location may begin to be determined. But this always happens for a very long time.

What does this error mean?

**Smartphone (please complete the following information):**
 - Device: Moto Z2 Force
 - OS: Android 8.0.0

**Additional context**
This code is part of the React Native application.

**Comment by PavelTychinin** [comment]
https://github.com/Navigine/Indoor-Positioning-And-Navigation-Algorithms/wiki/namespacenavigine_1_1navigation__core#types-documentation

That means that no visible beacons from selected location.

**Comment by Salma-Elmahallawy** [comment]
I am getting the same error on Google Pixel 4A (Android 11). Were you able to fix it?

**Comment by PavelTychinin** [comment]
> I am getting the same error on Google Pixel 4A (Android 11). Were you able to fix it? I do not get the same error on the app downloaded from the Play Store.

Hi Salma, thnx for your reply. Can you record logs inside app?

1) Select "v" button on Navigation fragment
2) Wait 1-2 min
3) Unselect "v" button
4) Open last tab and upload your logs


We will analyze them, and give an answer

**Comment by Salma-Elmahallawy** [comment]
> > I am getting the same error on Google Pixel 4A (Android 11). Were you able to fix it? I do not get the same error on the app downloaded from the Play Store.
> 
> Hi Salma, thnx for your reply. Can you record logs inside app?
> 
> 1. Select "v" button on Navigation fragment
> 2. Wait 1-2 min
> 3. Unselect "v" button
> 4. Open last tab and upload your logs
> 
> We will analyze them, and give an answer

Hi Pavel, my teammate has opened a new issue here #13 after further analyzing it. I am attaching the log there for your reference. Thanks!
